### ISSUE TITLE
Incomplete map upgrade

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11087]
While converting format 6 to 11 the following did not work:
* Removal of `UseAsShellmap: False`
* Removal of `Selectable: True`
* Removal of `Options: FragileAlliances: False`
* Translation of `Players: PlayerReference: Race:` to `Players: PlayerReference: Faction:`
* Conversion of actor health from float to int.

**Comment by pchote** [comment]
> Removal of Options: FragileAlliances: False 

The options block doesn't exist at all in format 11.  Are you saying that it somehow persisted after saving?

**Comment by Mailaender** [comment]
Yes, the whole one:

```yaml
Options:
	Crates: False
	Fog: True
	Shroud: True
	FragileAlliances: False
	AllyBuildRadius: False
	StartingCash: 5000
	ConfigurableStartingUnits: False
```
