### ISSUE TITLE
Expose CashTrickler trait in lua map script

### ISSUE THREAD

**Issue by mkondel** [OpenRA/OpenRA#11085]
It would be nice to have CaptureAmount, and the others, available in lua script.  The impact is minimal, I was trying to message players at the start of a game what amount they'd get, if they chose to capture certain buildings.
Example from map.yaml:
```
Actor131: ANCIENTSILO
    Owner: Neutral
    Location: 10,14

Rules:
    ANCIENTSILO:
        Inherits: silo
        CashTrickler:
            CaptureAmount: 2000
            Amount: 0
            ShowTicks: false
```
