### ISSUE TITLE
Combined sequences don't inherit defaults

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11213]
```yaml
northwestsoutheastbridge:
	idle:
		Combine:
			lobrdg01:
				UseTilesetExtension: true
```

works, but

```yaml
	Defaults:
		UseTilesetExtension: true
	idle:
		Combine:
			lobrdg01:
```

won't.
