### ISSUE TITLE
template 69 in cnc's snow.yaml and jungle.yaml is of size 1,1 but contains 3 tiles

### ISSUE THREAD

**Issue by tmsbrg** [OpenRA/OpenRA#11539]
I bumped into this while working on the map generator. Take a look at the template in jungle.yaml:
```yaml
	Template@69:
		Id: 69
		Images: p03.jun
		Size: 1,1
		PickAny: True
		Category: Debris
		Tiles:
			0: Wall
			1: Clear
			2: Clear
```

Size 1,1 but has 3 tiles? Seems wrong. Other tilesets whichs use the 69 template like temperat.yaml and desert.yaml each only define one tile. This caused a weird bug while working on my map generator. Placing these tiles with the generator caused completely black tiles to be added to the map. My current workaround is to just not place these tiles while adding debris.
