### ISSUE TITLE
[RA] Map uploaded in Resource Center, but lint check failed on all releases

### ISSUE THREAD

**Issue by Maurice84** [OpenRA/OpenRA#11659]
I've uploaded a Red Alert map called Four Districts in the Resource Center (http://resource.openra.net/maps/15071/), but unfortunately the lint check failed on all releases. It has been build with the Map Editor of release-20160508, but I've been finalizing it in the most recent OpenRA-bleed (Github)

How can I debug the map? How can I know what t02.husk is so I can remove it?

Lint check for release-20160508
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
Errors: 4

Lint check for release-20151224
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
OpenRA.Utility(1,1): Error: Actor t02.husk is not defined by any rule.
Errors: 4

Lint check for git-c2ec0d3
OpenRA.Utility(1,1): Error: Failed with exception: System.IO.FileNotFoundException: Unable to find parent package for /Web/openra/sites/resource.openra.net/www/openra/data/maps/15071/FourDistricts.oramap
at OpenRA.FileSystem.ZipFile..ctor (IReadOnlyFileSystem context, System.String filename) [0x00076] in /home/servers/servers/tmp/bleed/OpenRA.Game/FileSystem/ZipFile.cs:64 
at OpenRA.FileSystem.FileSystem.OpenPackage (System.String filename) [0x00050] in /home/servers/servers/tmp/bleed/OpenRA.Game/FileSystem/FileSystem.cs:47 
at OpenRA.Mods.Common.UtilityCommands.CheckYaml.Run (OpenRA.ModData modData, System.String[] args) [0x00000] in :0

**Comment by obrakmann** [comment]
Remove these entries from your map.yaml file:
```yaml
Actor300: t02.husk
	Owner: Neutral
	Location: 161,161
Actor311: t02.husk
	Owner: Neutral
	Location: 163,172
Actor312: t02.husk
	Owner: Neutral
	Location: 174,159
Actor313: t02.husk
	Owner: Neutral
	Location: 174,145
```
