### ISSUE TITLE
Trike and Raider muzzle flashes not visible

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12270]
The sequences start at the right frame of DATA.R8, so it must be something else.

**Comment by ltem** [comment]
Adding `Projectile: Bullet` to `HMG_muzzle:`/`HMGo_muzzle:` in "/mods/d2k/smallguns.yaml" fixes this bug for me ... so it looks like this:
```yaml
HMG_muzzle:
	ReloadDelay: 16
	Range: 3c0
	Projectile: Bullet
	Burst: 3
	BurstDelay: 2
	Warhead@TargetValidation: SpreadDamage
```
Took me quite some time to narrow it down to this and I'm not using C#, so reading the trait-files didn't really help but maybe `Projectile:` is needed to trigger the muzzle sequence?!

Maybe this can also be squeezed into #12515...
