### ISSUE TITLE
UncloakOn: value for External Capturing

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13767]
On Generals cloaked infantry would uncloak when capturing something. This is a balancing issue for me on the mod i'm working on as GLA Rebels can be upgraded to be cloaked.

**Comment by gwenzek** [comment]
I'd like to implement this as my first PR to OpenRA.
As far as I understand, I'll need to:

- Add a `INotifyExternalCapture` notifier with two events (OnCapturing, OnCaptured)
- Add a `ExternalCapturing` type to the `UncloakType` enum.
- Implement the `INotifyExternalCapture` in the `Cloak` class.
- Write the code that fires the event when the capture begins (not sure how to do that).

I have a few questions:
- what's the difference between `Captures` and `ExternalCaptures` ?
 `Captures` is used by the CnC engineer while `ExternalCaptures` for the RA engineer
- should they be merged ?
- if no, should I implement the uncloaking ability for both type of captures ?
  Note that 'Captures' already have a notifier but only notifies once the capture is done,
  while I understand that the feature is about un-cloaking when the capture starts.

**Comment by MustaphaTR** [comment]
Difference between Captures and ExternalCaptures is;

For captures unit enters the target that will be captured, as in vanilla TD to RA2.

For external captures unit captures outside the building, and waits for a while to capture, as in vanilla Generals.

**Comment by abcdefg30** [comment]
I don't think we need this for `Captures` as capturing actors are consumed.

> Write the code that fires the event when the capture begins (not sure how to do that).

I'd suggest you add the calls to the interface somewhere [here](
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/ExternalCaptureActor.cs#L53). You look at #13639 if you need an example.

**Comment by MustaphaTR** [comment]
This got fixed by #13854

**Comment by gwenzek** [comment]
Here is a sample of YAML config I used for testing the feature.
It didn't get implemented as you requested so you have to do the following:

``` YAML
  ExternalCaptures:
    CaptureTypes: building
    PlayerExperience: 25
    CapturingCondition: capturing
  Cloak:
    InitialDelay: 250
    CloakDelay: 120
    UncloakOn: Attack, Unload, Infiltrate, Demolish
    CloakTypes: Cloak
    IsPlayerPalette: true
    RequiresCondition: !capturing
```
