### ISSUE TITLE
"Error: Map contains invalid custom rules." hides the linter error

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#14030]
It only says `OpenRA.Utility(1,1): Error: Map contains invalid custom rules.` instead of pointing to what actually failed. I first really noticed it during #13934, where Monster Tank Madness just gave this not helpful at all error, because a required field (`IntoActor`) wasn't set for `5tnk.husk`. I believe it is also one of the reasons for bad performance of the lint checks. The ones during ruleset loading are at least conflicting and probably even duplicating the effort making it way too expensive.

**Comment by SevaJmurov** [comment]
I get this error even if I have incorrect syntax in map's yaml files.
Is this due to regression? 
I don't know how it was working earlier, but I expected Utility to return error details (e.g. row, column).

**Comment by Mailaender** [comment]
> I get this error even if I have incorrect syntax in my yaml files.

Can you upload your files?

**Comment by SevaJmurov** [comment]
Not sure if other files are relevant, this is settings.yaml. In map.yaml I've got:
```yaml
...
Rules: rules/settings.yaml
```
If I have extra tab or unwanted spaces in this file(for instance no tab before "Name" property of the pallete).

```yaml
	WeatherOverlay:
		ChangingWindLevel: true
		WindLevels: -2, 0, 2#-7, -5, 5, 7
		WindTick: 150, 550
		InstantWindChanges: false
		UseSquares: true
		ScatterDirection: 0, 0
		ParticleSize: 0, 1
		Gravity: 1.00, 1.00
		SwingOffset: 1, 1.001
		SwingSpeed: 0.001, 0.0015
		SwingAmplitude: 1, 1.015
		ParticleColors: D5C200, D5A100, D87F00, C6B700
	GlobalLightingPaletteEffect:
		ExcludePalettes: cursor, chrome, colorpicker, fog, shroud, alpha
		Red: 1.05
		Green: 1.05
		Blue: 1
		Ambient: 1.15

^Palettes:
	PaletteFromFile@ra_units:
		Name: ra_units
		Filename: ratemp.pal
		ShadowIndex: 4
		RemapIndex: 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95
```

then I get the many messages like:
```OpenRA.Utility(1,1): Error: Actor <custom_actor> is not defined by any rule.```
followed by the above-mentioned message.

Maybe I'm not getting the point of this thread, but I thought it should throw error on incorrect syntax and stop further map check.

Also I found that if I'm trying to pass anything but absolute path to map as a parameter for --check-yaml I get this:
```
OpenRA.Utility(1,1): Error: Failed with exception: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Map..ctor (OpenRA.ModData modData, OpenRA.FileSystem.IReadOnlyPackage package) [0x00053] in <adccc5d07c144774863d73ace7658d93>:0 
  at OpenRA.Mods.Common.UtilityCommands.CheckYaml.OpenRA.IUtilityCommand.Run (OpenRA.Utility utility, System.String[] args) [0x00216] in <3deaf9d94b2f400b8afbb2c9cedb1118>:0 
```
