### ISSUE TITLE
How do I use ExternalCaptures trait?

### ISSUE THREAD

**Issue by SevaJmurov** [OpenRA/OpenRA#14207]
Hi.
I'm trying to change TD mod's engineers behaviour so that he could capture buildings externally, as he currently does in RA mod. ExternalCapture... traits seem to be common for all mods, so I presume they should work in TD.
I've checked how this implemented in RA and added this:

```yaml
^Building:
	ExternalCapturable: 
		CaptureCompleteTime: 30	
	ExternalCapturableBar:

E6.ec:
	Inherits: E6
	Tooltip
		Name: Engineer for external capture
	RenderSprites:
		Image: E6
	ExternalCaptures:
		CaptureTypes: building
		PlayerExperience: 50
		CaptureCursor: ability
```

to my map's rules.yaml

I've played around with this trait's properties, added and removed them different ways (Type, Allow etc.) though seems like it should have worked with defaults.

Nothing of this changes engie's behaviour in game, not even cursor. Is this even possible to achieve in TD?

**Comment by pchote** [comment]
You will need to remove the standard capturing traits too, otherwise they will probably take precedence over the external capturing.

**Comment by SevaJmurov** [comment]
As I can't(don't know how) remove mod traits from custom map's rules. I decided to describe a new unit:

```yaml
^Building:
	ExternalCapturable:
		Type: building
		CaptureCompleteTime:30
		AllowEnemies: true
		AllowAlies: true
		AllowNeitral: true
	ExternalCapturableBar:

ENGY:
	Inherits: ^Soldier
	Valued:
		Cost: 500
	Tooltip:
		Name: New engineer
	RenderSprites:
		Image: E6
	Buildable:
		BuildPaletteOrder: 30
		Prerequisites: barracks
		Queue: Infantry.GDI, Infantry.Nod
		Description: Captures enemy structures externally.\n  Unarmed
	Mobile:
		Speed: 48
	Health:
		HP: 30
	Passenger:
		PipType: Yellow
	EngineerRepair:
	RepairsBridges:
	ExternalCaptures:
		CaptureTypes: building, husk
		PlayerExperience: 50
		CaptureCursor: ability
```
Works like a charm!

I will make standard engineer unbuildable, I guess.
