### ISSUE TITLE
Engineer d2k

### ISSUE THREAD

**Issue by Alex34567889** [OpenRA/OpenRA#14763]
Hello! Is it possible for a bot to create an engineer? I wrote in ai.yaml but they do not send it to buildings

**Comment by MustaphaTR** [comment]
There is a engineer handling code fr AI but it doesn't work reliably so we don't use it on default mods. Refer to HackyAI section of traits wiki page to see related tags.

**Comment by StormWingDelta** [comment]
I've gotten the AI to capture things with the engineer but it takes some tinkering with the capture code.  I'm working on the AI's code with others right now so feel free to shoot ideas into the PR.  One thing I've noticed yet can't figure out how to prevent is the AI will gather engineers for squads but refuse to use their abilities to capture anything.

In any event here's some yaml code that I know works for getting the Engineer in all 3 mods to capture something as long as the squad size is 10+

```yaml
		CapturingActorTypes: e6, mech, hijacker
		CapturableActorTypes:
		MinimumCaptureDelay: 300
		MaximumCaptureTargetOptions: 25
		CheckCaptureTargetsForVisibility: false
		CapturableStances: Enemy, Neutral
```

Again like MustaphaTR said it still is unreliable but it does work, now keep in mind under UnitsToBuild you do still need the engineer named under there, it's either engineer: somenumber% or e6: somenumber%, don't forget to limit how many it can make under UnitLimits because for some odd reason it'll spam the heck out of them. O_o
