### ISSUE TITLE
Changing map to a map with different non-forced default values don't change the option

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15545]
On my mod i have Tank General Challange map which has different default values ($13000 Starting Cash and Crates Disabled) but they aren't locked and can be changed. When i change from a normal map to challange map, those options still stay as mod defaults ($10000 and Crates Enabled). If challange is the map selected when i open the lobby it sets the defaults properly.

**Comment by swtya** [comment]
They lobby options have been bugging me for a while when attempting to set map specific default values. This ticket looks similar to #20556.

I think I can demonstrate using the unexpected behaviour with the PlayerResources of SelectableCash and DefaultCash.
I'd been hoping that when selecting a new skirmish that any specifically set parameters of the map rules would be used in the lobby.

The use of the "LOCKED" flag is not obvious from the online documentation and also makes the value non-variable after loading which is restrictive. Notably for Cash and Tech levels, these are desirable to be flexible when a user is setting up a skirmish. Further when moving away from a map to one with non-locked options the value persists despite the user not having made a positive selection.

Hypothesis, same map just differing the starting cash. From the lobby selecting each map I'd expect the default starting cash drop-down to be prepopulated without further user interaction. If this was an intentional design decision please reference to avoid duplication/repetitive analysis.

Hard version = less cash in the default
```
Rules:
    Player:
        PlayerResources:
            # SelectableCash: 2500, 5000, 10000, 20000    # Issue 1
            SelectableCash: 2500, 10000, 20000          # Issue 2
            # SelectableCash: 2501, 5001, 10001, 20001    # Issue 2a
            DefaultCash: 2500                           # Issue 1 & 2
            # DefaultCash: 2501                           # Issue 2a
            DefaultCashDropdownVisible: True
            DefaultCashDropdownLocked: False            # True or False
```

Easy version = more cash in the default
```
Rules:
    Player:
        PlayerResources:
            # SelectableCash: 2500, 5000, 10000, 20000    # Issue 1
            SelectableCash: 2500, 10000, 20000          # Issue 2
            # SelectableCash: 2502, 5002, 10002, 20002    # Issue 2a
            DefaultCash: 10000                          # Issue 1 & 2
            # DefaultCash: 10002                          # Issue 2a
            DefaultCashDropdownVisible: True
            DefaultCashDropdownLocked: False            # True or False
```

Put the above texts at the end of the respective map.yaml files.

Issue 1: DefaultCash not updated.
Launch OpenRA, SinglePlayer, Skirmish -> selecting either map the cash value is not honoured as the system likes 5000 for no documented reason. By inspection the last lobby settings are being recalled from "skirmish.ra.yaml" in .config/openra/. 

Issue 2: Remove the 5000 number from the SelectableCash in each file. Select the hard map. Now as the cached value from "skirmish.ra.yaml" is not found it will pick the DefaultCash number of 2500. However moving to the other map (easy) it then remains as the 2500 because 10000 is in both map SelectableCash lists. So this initially gives the appearance of doing what was hoped for, but not really.
Issue 2a: Continuing this approach one could make all the values unique, in each map, but that will again come unstuck at some point where two of the same are switched between.

Issue 3: The "Reset Defaults" button, does two things, it resets the all the values and then applies the map values - so questioning what does "Default" mean as it's map dependant. 


Notes for consistent reproduction, I'm using AppImage_20250330, before launching application:
a) Before closing select, official map, A Nuclear Winter.
b) Delete the skirmish.ra.yaml, to remove legacy settings so there are no cached values to ensure reproduceability.
c) Edit the map files for the test.
d) Launch RA AppImage and make observations.


Possible solutions:
1) Remove all attempts at caching the lobby if the map changes, i.e. automatically apply "Reset Defaults".
    Pro: Map file gets consistent loading without bias from previous map file.
    Con: User will have to re-load their favourite settings. Software coding effort when the user can already press a button.
2) Upon a map change only apply the lobby values specified in the map file, retaining everything else.
    Pro: Retains user lobby settings not pushed from map. Less aggressive than "Reset Defaults" workaround.
    Con: Modified behaviour to user, the "lock" method not required to pick map value. Does not resolve custom lobby value retention between map changes.
2) Make the lobby values a full per-map cache, using the map hash. In settings.yaml each game contains the last active map - can this be re-used as an index?
    Pro: Probably what the user wants. Full settings retained between maps, even when some maps add or remove custom lobby options. This will also fix the issue where if the lobby is setup with 4 players and a 2 player map is selected and returned to 4 player the players are reset (as the cache deleted players 3 & 4.
    Con: More software coding and larger skirmish.ra.yaml file, it will grow with the user map folder.
