### ISSUE TITLE
TS Conyards and MCV don't honor emp-disable

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16420]
MCV needs 
```yaml
	Mobile:
		PauseOnCondition: empdisable
	Transforms:
		PauseOnCondition: empdisable
```
Conyards need
```yaml
	Transforms:
		PauseOnCondition: being-demolished || empdisable
```
