### ISSUE TITLE
ChangeOwnerWarhead fired by an IonCannonPower ignores InvalidTargets

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#17954]
Intended is that only Vehicles get affected, as given. Have tried various combination of ValidTargets: and InvalidTargets:  hasnt made any difference.
```
	IonCannonPower@InstantHijacker:
		PauseOnCondition: disabled || lowpower
		OrderName: InstantHijacker
		Prerequisites: ~stek, player.soviet
		Icon: hijacker
		ChargeInterval: 10500
		Description: Hijacker
		LongDesc: Targeted enemy Vehicle changes\nside to your faction permanently.
		CameraActor: dummy.qtnk
		OnFireSound: smout1.aud
		Cursor: airstrike
		DisplayRadarPing: True
		SupportPowerPaletteOrder: 2
		Effect: skull-red
		EffectSequence: derp
		EffectPalette: effect
		Weapon: StealVehicle
		WeaponDelay: 0
```
```
StealVehicle:
    Warhead@2OwnerChange: ChangeOwner
        Range: 0c512
        Duration: 0
        InvalidTargets: Infantry, Structure, Ship, Aircraft
```
