### ISSUE TITLE
Yak freezes in air above submerged submarine

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#18923]
Reported by user Panrac on the discord server.

[Playtest_20201213-Bug-Greece-YakOverSub_1045_1530.orarep.zip](https://github.com/OpenRA/OpenRA/files/5685322/Playtest_20201213-Bug-Greece-YakOverSub_1045_1530.orarep.zip)

<img width="281" alt="Screenshot 2020-12-13 at 19 53 00" src="https://user-images.githubusercontent.com/167819/102022202-1a840c80-3d7d-11eb-8489-9b0ce62db890.png">

At 10:45 - 15:30 in the replay a bot yak is trying to attack submerged bot submarines in the bottom-right corner of the map.  It flies above the submarine and then stops mid-air for many seconds before circling again and repeating.

Probably a regression from #17935.

**Comment by abcdefg30** [comment]
Possibly fixed by #18511?

**Comment by pchote** [comment]
Looks like it should be, but we'll need a non-replay repro case (which probably isn't hard) to confirm that.

**Comment by pchote** [comment]
This is happening because:

https://github.com/OpenRA/OpenRA/blob/71b13c7b5de1ff9682124f92d5345d8a0c67231e/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs#L93

has a hardcoded workaround that makes bot ignore visibility, meaning that `targetIsHiddenActor` is false even though the actor is cloaked.

It therefore executes this branch

https://github.com/OpenRA/OpenRA/blob/71b13c7b5de1ff9682124f92d5345d8a0c67231e/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs#L97-L103

but assigns `lastVisibleMaximumRange = 0` (presumably because `GetMaximumRangeVersusTarget` isn't ignoring the cloak?)

This then causes the following to misbehave:

https://github.com/OpenRA/OpenRA/blob/71b13c7b5de1ff9682124f92d5345d8a0c67231e/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs#L143-L152

The `IsInRange` check always returns false (because of the zero range), so it queries a `Fly` to `checkTarget.CenterPosition`, which is equal to `self.CenterPosition`, meaning that it doesn't move.

**Comment by pchote** [comment]
This suggests that #18511 won't help because `FlyAttack` is failing before it gets to queue those child activities.

**Comment by pchote** [comment]
Repro case: add the following actors to the RA Snow Town map, then spectate a bot-vs-bot game (bots must be in the first two slots).

```yaml
       Actor246: ss
               Faction: allies
               Location: 87,39
               Owner: Multi0
               Facing: 384
       Actor247: ss
               Faction: allies
               Location: 85,41
               Owner: Multi1
               Health: 1
               Facing: 384
       Actor248: yak
               Faction: allies
               Location: 92,36
               Owner: Multi1
               Stance: AttackAnything
               Facing: 384
```
