### ISSUE TITLE
YAML `Inherits` works only at the actor level

### ISSUE THREAD

**Issue by muppet9010** [OpenRA/OpenRA#19580]
### Issue
The Inherits attribute in ai.yaml isn't substituted out for the named anchor. Instead the `Inherits: ^ANCHOR` ends up in the parsed YAML. Encountered when trying to add my own AI's to CnC 

### Example - Small Scope
Example code added to the end of CnC ai.yaml:
```
Player:
    ...
    McvManagerBotModule@muppet-ai-mcv-expand-none:
        RequiresCondition: enable-muppet-ai-mcv-expand-none
        Inherits: ^SquadManagerBotModuleMuppet
        MinimumConstructionYardCount: 1            # Never force it to expand.
    McvManagerBotModule@muppet-expand-1:
        RequiresCondition: enable-muppet-ai-expand-1
        McvTypes: mcv
        ConstructionYardTypes: fact
        McvFactoryTypes: weap,afld
        RestrictMCVDeploymentFallbackToBase: true
        MinBaseRadius: 30
        MaxBaseRadius: 40
        MinimumConstructionYardCount: 2            # Force some multi baseness - but is still a bit random end result so can end up with more from simultanious building.
...
^SquadManagerBotModuleMuppet:
    McvTypes: mcv
    ConstructionYardTypes: fact
    McvFactoryTypes: weap,afld
    RestrictMCVDeploymentFallbackToBase: true
    MinBaseRadius: 30
    MaxBaseRadius: 40
```

The returned code from the OpenRA Utility with `--resolved-rules Player` shows the Inherits still in it.
![image](https://user-images.githubusercontent.com/40836017/128081098-f4ba8a3c-bd48-4d70-8867-221c46085dbc.png)

### Example - Full Usage Issue
Attached is the full ai.yaml for CnC I was testing. The Anchors and Inherits are all at the end of the file.
[ai.yaml.txt](https://github.com/OpenRA/OpenRA/files/6926844/ai.yaml.txt)
In this file the AIs that is controlled by the module `McvManagerBotModule@muppet-ai-mcv-expand-none` and uses the Inherits in its code is idle in game. The AI's that use the other `McvManagerBotModule` modules which has the full code are active. When I swap out which module use Inherits vs the full code the associated AI's start/stop working.
