### ISSUE TITLE
Hotkey contexts for easier validation and improved mental model

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#19898]
## Motivation

Currently there's a `Types` hash set on hotkey definitions that is used for two very different things - grouping the entries visually in the settings panel and validating the keys for overlap. The initial use was just for grouping but validation was tacked on later (in #16552). Validation is achieved by adding the keys to "hidden groups" (i.e. types that don't show up in the UI). Here's an example:
```yaml
MapScrollUp: UP
    Description: Scroll
    # This key is part of the "Viewport" group in the UI 
    # but is validated against the hidden "Player" and "Spectator" groups
    Types: Viewport, Player, Spectator
```

This is not great not just code-wise but also because how a key is validated is not transparent to the user. The user only sees the visible groups and not the hidden validation logic.

## Proposed solution

A solution is to split these two functionalities by adding a new "context" field to the definitions:

```yaml
MapScrollUp: UP
    Description: Scroll
    # Grouping in the UI
    Types: Viewport
    # Context for validation
    Contexts: Player, Spectator, Editor
```
I have identified several contexts:
- Player
- Spectator
- Editor
- Menu
- Chat

Once we have that set up we can use it to expose the contexts (and thus the validation logic) to the user. Something like this:
![image](https://user-images.githubusercontent.com/1355810/150693976-efab48ad-c71b-4aa4-95cd-1489257c1dec.png)

The UI needs some more thought - this is just a quick mock-up to illustrate the idea.
