### ISSUE TITLE
YAML merging - overriding collections

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#21837]
Transferred from a [Discord discussion starting here](https://discord.com/channels/153649279762694144/968593812794531892/1357452725373243575).

> imagine TraitInfo has a field that is an array
default structure rules specify 3 values for that array
mission overrides to 2 values

Scenario 1 - just do it:
![Image](https://github.com/user-attachments/assets/c38eb2d5-4229-4f12-8f87-9c5ddf38d13c)
✅ This leads to the two arrays being merged, so end result is still 3 values (assuming keys match, overriding the original ones); otherwise it can result in 5 values.

Scenario 2 - remove and readd:
![Image](https://github.com/user-attachments/assets/20ff1b23-3d57-48c5-b106-0dd1d8cb1662)
❌ This throws a "duplicate key exception" for "Squad".
_**EXPECTED:**_ Remove the inherited collection, add the new one.

Scenario 3 - remove unnecessary values:
![Image](https://github.com/user-attachments/assets/162fc39d-b108-4a33-8375-4c4f5628ed9e)
✅ This actually works as expected - merges the two collections like `Scenario 1`, removing the "@2" element.

**_Ideally `Scenario 2` and `Scenario 3` should produce the same result in this example._**

As a unit test this would look like this:
```yaml
Test:
    MockString:
        CollectionOfStrings:
            String@1: A
            String@2: B
Test:
    MockString:
        -CollectionOfStrings:
        CollectionOfStrings:
            String@1: C
```
