### ISSUE TITLE
 Unit does not have sequence defined always errors about the first, not the real one that is missing

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3602]
`System.InvalidOperationException`: Unit `weedguy` does not have sequence `stand` defined.

```yaml
weedguy:
	stand: weed
		Start: 0
		Facings: 8
		ShadowStart: 202
	run: weed
		Start: 8
		Length: 6
		Facings: 8
		Tick: 100
		ShadowStart: 210
	shoot: weed
		Start: 56
		Length: 1
		Facings: 8
	prone-shoot: weed
		Start: 212
		Length: 6
		Facings: 8
	standup-0: weed
		Start: 260
		Length: 2
		Facings: 8
	prone-run: weed
		Start: 86
		Length: 4
		Facings: 8
		Tick: 100
		ShadowStart: 288
	prone-stand: weed
		Start: 144
		Length: 4
		Facings: 8
		ShadowStart: 346
	die1: weed
		Start: 160
		Length: 6
		ShadowStart: 336
	die2: weed
		Start: 149
		Length: 14
		ShadowStart: 351
	die3: weed
		Start: 166
		Length: 10
		ShadowStart: 368
	die4: weed
		Start: 197
		Length: 5
		ShadowStart: 399
	die5:
		Start: 177
		Length: 19
		ShadowStart: 379
	die6: electro
		Start: 0
		Length: *
```

I just forgot about `die5`, but the wrong message thrown is just confusing here.
