### ISSUE TITLE
Remove magic sprite filename resolution (support TS-style terrain-specific artwork) [$20]

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#5272]
Automatically resolving extensionless filenames to tileset-specific versions made sense back in 2007, but the engine is now a completely different beast and this now causes more problems than it solves.

* It makes it very difficult to statically verify sequence errors. #2283
* It makes it difficult to effectively cache data to reduce load times (see #5234).
* It's not needed for D2K, which doesn't have tileset-specific art.
* It won't work at all in TS or RA2, which use different names (not just extensions) for tileset-specific art.

We should rip out this legacy code, require mods to define tileset-variants in sequences, and then use name mangling (like we do for damage states) to resolve them in mod-level code.

**Comment by pchote** [comment]
We can minimize the additional boilerplate required by adding a `Variant` property that overrides the default sprite filename:

e.g.:
```yaml
mslo:
	idle: mslo.tem # default to this if a tileset-specific variant isn't found
		Variants:
			SNOW: mslo.sno
			DESERT: mslo.des
		Start: 0
```
or
```yaml
gacnst:
	idle: gtcnst.shp
		Variants:
			SNOW: gacnst.shp
		Start: 0
		ShadowStart: 3
		Offset: 0, -36
```
