### ISSUE TITLE
Misleading sequence exception.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#6975]
``` yaml
gacnst:
    idle: ggcnst
        Start: 0
        ShadowStart: 3
        Offset: 0,-55,0
    make: ggcnstmk
        Start: 0
        Length: 28
        ShadowStart: 28
        Offset: 0,-55,0
    damaged-idle: ggcnst
        Start: 1
        ShadowStart: 4
        Offset: 0,-55,0
    idle-fans: ggcnst_a
        Start: 0
        Length: 6
        Tick: 150
        Offset: 0,-55,0
    damaged-idle-fans: ggcnst_a
        Start: 5
        Length: 6
        Tick: 150
        Offset: 0,-55,0
    crane-overlay: ggcnst_b
        Start: 0
        Length: 20
        Tick: 150
        Offset: 0,-55,0
    damaged-crane-overlay: ggcnst_b
        Start: 20
        Length: 20
        Tick: 150
        Offset: 0,-55,0
    icon: xxicon
        Start: 0
```

Throws with: `System.InvalidOperationException`: Unit `gacnst` does not have a sequence named `make`.

This should instead tell the user that the file `ggcnstmk` does not exist.
##
