### ISSUE TITLE
Support for using individual files for each frame of a sequence

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7666]
Example to explain what I mean:

Assume there are 64 single-frame shps (or GIFs or PNGs, once they're supported), let's say htnk01.shp - htnk64.shp -> treated by the engine like a single htnk.shp container.
bogus yaml code:
http://pastebin.com/SsFGjh4H

While this might be more costly performance-wise, it would make adding support for non-multi-frame formats easier (PNG probably being the most interesting option), and would also make life for modders easier because they could exchange individual frames more easily, quite convenient when your graphics are still work-in-progress.

**Comment by pchote** [comment]
I have added support for aggregate sequences in one of my development branch.
It requires more boilerplate than your example yaml, but it is more general (see e.g. #6631):
```yaml
htnk:
	idle:
		Combine:
			htnk01:
			htnk02:
			...
			htnk31:
			htnk32:
		Facings: 32
	turret:
		Combine:
			htnk33:
			htnk34:
			...
			htnk63:
			htnk64:
		Facings: 32
```
