### ISSUE TITLE
Inheriting DefaultVariant does not work in voices.yaml

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#8185]
```yaml
    ^DefaultVoice:
	Voices:
		Burned: dm01
		Zapped: igenzapa
	Variants: .WAV
	DefaultVariant: .wav

    SovietMCVVoice:
	Inherits: ^DefaultVoice
	Voices:
		Select: vmcssea, vmcsseb, vmcssec, vmcssed, vmcssee
		Move: vmcsmoa, vmcsmob, vmcsmoc, vmcsmod, vmcsmoe
		Attack: vmcsmoa, vmcsmob, vmcsmoc, vmcsmod, vmcsmoe`
```
used in voices.yaml results with
```
Attempt to Play2D a null `ISoundSource`
LoadSound, file does not exist: vmcssed.aud
Attempt to Play2D a null `ISoundSource`
LoadSound, file does not exist: vmcssec.aud
```
messages.

I don't think that's supposed to happen. The wavs are loose and bits reference lists their folder.
