### ISSUE TITLE
Prevent running an upgrade rule on already-upgraded rules.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#8798]
I've planned this for quite a few months but finally decided to make an issue instead of doing it myself when I have free time (which is almost never).

My idea is a comment at the top of the file that indicates the last version that the rules were updated to.
Then the upgrader reads this line and won't run any rules that would have already been ran.
This should of course be overrideable (either via flag or just removing the line).

``` yaml
#20150614

engineer:
        Inherits: ^Infantry
        Buildable:
                Queue: Infantry
                BuildPaletteOrder: 60
        Valued:
                Cost: 500
        Tooltip:
                Name: Engineer
                Description: Captures enemy structures.\n  Unarmed
        Selectable:
                Bounds: 20, 30, 0, -11
        Health:
                HP: 75
        Mobile:
                Speed: 56
        Passenger:
                PipType: Blue
        EngineerRepair:
        RepairsBridges:
        Captures:
                CaptureTypes: building, husk
        -AutoTarget:
        WithInfantryBody:
        RevealsShroud:
                Range: 4c0
        Voiced:
                VoiceSet: AlliedEngineerVoice
```

Or maybe start the line with `#%` or similar to indicate the line is special, or have metainfo such as:
`# last-rule: 20150614`
##
