### ISSUE TITLE
Sequence inheritance MiniYaml merging [$15]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8890]
Like we do for rules as proposed in https://github.com/OpenRA/OpenRA/pull/8799#issuecomment-126936258.

**Comment by Phrohdoh** [comment]
Investigation:

**Using ActorInfo as a basis**:

**Constructor**: `ActorInfo(string name, MiniYaml node, Dictionary<string, MiniYaml> allUnits)`

`name`: The actor definition's top-level node's key. (`E1`, `Medic`, etc)

`node`: The `MiniYaml` representation of the textual definition
```yaml
E1:
	Inherits: ^Soldier
	Buildable:
		Queue: Infantry
		BuildPaletteOrder: 10
		Prerequisites: ~barracks
```
```yaml
key:
	key: value
	key:
		key: value
		key: value
		key: value
```

`allUnits`: A dictionary with keys that are `ActorInfo.Name.ToLowerInvariant()`s
```yaml
# This dict contains (as the name suggests) *all* definitions as MiniYaml structures
allUnits["e1"] =
E1:
	Inherits: ^Soldier
	Buildable:
		Queue: Infantry
		BuildPaletteOrder: 10
		Prerequisites: ~barracks
...
```

Snippet from `ActorInfo`'s ctor:
```csharp
				// Guard against circular inheritance
				allParents.Add(name);
				var mergedNode = MergeWithParents(node, allUnits, allParents).ToDictionary();

				Name = name;

				foreach (var traitNode in mergedNode)
				{
					...
				}
```

```csharp
		static MiniYaml MergeWithParents(MiniYaml node, Dictionary<string, MiniYaml> allUnits, HashSet<string> allParents)
		{
			var parents = GetParents(node, allUnits);
			...
		}
```

```csharp
		static Dictionary<string, MiniYaml> GetParents(MiniYaml node, Dictionary<string, MiniYaml> allUnits)
		{
			return node.Nodes.Where(n => n.Key == "Inherits" || n.Key.StartsWith("Inherits@"))
				.ToDictionary(n => n.Value.Value, n =>
			{
				MiniYaml i;
					if (!allUnits.TryGetValue(n.Value.Value, out i))
						throw new YamlException(
							"Bogus inheritance -- parent type {0} does not exist".F(n.Value.Value));

				return i;
			});
		}
```

All appears fine and dandy with borrowing this approach except for a small difference.

* Sequences are parsed (**once!**) top-down and independently of one-another
* Actor definitions are parsed in two phases:
  * Creating the relevant `Dictionary<string, MiniYaml>` from files on disk
  * Building `ActorInfo`s from the existing dictionaries

This means ActorInfos have access to all other relevant MiniYaml structures they may need while sequences have absolutely no extra information.

---

`DefaultSpriteSequence.ParseSequence`:
```csharp
		public IReadOnlyDictionary<string, ISpriteSequence> ParseSequences(ModData modData, TileSet tileSet, SpriteCache cache, MiniYamlNode node)
		{
			var sequences = new Dictionary<string, ISpriteSequence>();
			var nodes = node.Value.ToDictionary();

			MiniYaml defaults;
			if (nodes.TryGetValue("Defaults", out defaults))
			{
				nodes.Remove("Defaults");
				nodes = nodes.ToDictionary(kv => kv.Key, kv => MiniYaml.MergeStrict(kv.Value, defaults));

				foreach (var n in nodes)
					n.Value.Value = n.Value.Value ?? defaults.Value;
			}

			...

			return new ReadOnlyDictionary<string, ISpriteSequence>(sequences);
		}
```

The important lines here are:
```csharp
				foreach (var n in nodes)
					n.Value.Value = n.Value.Value ?? defaults.Value;
```

Which of course uses the values found in `Defaults` for a key if the key is omitted.
This is similar to what we are after but still lies in its own little world with no knowledge of other sequences.

---

**Why I cannot do anything with this information**:

I cannot make out where we are constructing `allUnits`, but I feel if we rewrite sequence parsing to be a two-step process we basically get all of the merging logic for free as it already exists for `ActorInfo` construction
