### ISSUE TITLE
GDI's gactwr does not accept tower.vulcan upgrade via Lua.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#8950]
```yaml
	tower1: gactwr
		Location: 42,13
		Owner: player
		Health: 100
		Facing: 160
	tower2: gactwr
		Location: 42,17
		Owner: player
		Health: 100
		Facing: 160

Rules:
	World:
		-CrateSpawner:
		-SpawnMPUnits:
		-MPStartLocations:
		LuaScript:
			Scripts: map.lua
		ScriptUpgradesCache:
			Upgrades: tw_up
		-StartGameNotification:
```

```lua
WorldLoaded = function()
	local tw_up = "tower.vulcan"

	if tower1.HasProperty("AcceptsUpgrade") then
		if tower1.AcceptsUpgrade(tw_up) then
			tower1.GrantUpgrade(tw_up)
		else
			Media.DisplayMessage("t1 doesn't accept " .. tw_up)
		end
	else
		Media.DisplayMessage("t1 doesn't accept upgrades")
	end

	if tower2.HasProperty("AcceptsUpgrade") then
		if tower2.AcceptsUpgrade(tw_up) then
			tower2.GrantUpgrade(tw_up)
		else
			Media.DisplayMessage("t2 doesn't accept " .. tw_up)
		end
	else
		Media.DisplayMessage("t2 doesn't accept upgrades")
	end
end
```

In-game I get `t1 doesn't accept tower.vulcan` and `t2 doesn't accept tower.vulcan`.

For completeness this is the trait that should accept `tower.vulcan` that is currently on `gactwr`:
```yaml
	Armament@VULCPRIMARY:
		UpgradeTypes: tower.vulcan
		UpgradeMinEnabledLevel: 1
		Weapon: VulcanTower
		LocalOffset: 768,85,512
		MuzzleSequence: muzzle
		MuzzleSplitFacings: 8
```
