### ISSUE TITLE
Support mods loaded from the support directory

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8992]
This is another fundamental engine feature for third party mods.  Expecting players to install mods in the main game dir is dangerous, and causes trouble when we release new engine versions.  Loading mods from the support dir fixes most of these problems.

We should support both unpacked mods (in a directory) and packaged mods in a zip renamed to oramod.
Because these mods are effectively data files in a user-owned directory there are no fundamental problems with supporting in-game installation and upgrades for them.

The tricky part is dealing with file paths, as our current mod.yaml syntax defines only `.` for "relative to game exe" and `^` for "relative to support dir".  I propose introducing a `<mod id>:` prefix for referencing files relative to the current or another named mod dir.

e.g. a snippet of the d2k mod may look like:
```yaml
Assemblies:
	common: OpenRA.Mods.Common.dll
	ra: OpenRA.Mods.RA.dll
	cnc: OpenRA.Mods.Cnc.dll
	d2k: OpenRA.Mods.D2k.dll

ChromeLayout:
	d2k: chrome/install.yaml
	d2k: chrome/ingame.yaml
	ra: chrome/ingame-chat.yaml
	ra: chrome/ingame-diplomacy.yaml
	ra: chrome/ingame-fmvplayer.yaml
	d2k: chrome/ingame-menu.yaml
	ra: chrome/ingame-info.yaml
	ra: chrome/ingame-infoscripterror.yaml
```
