### ISSUE TITLE
Add mod browser support for querying third party mod versions.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9028]
This feature has already been requested by our budding modding community, and is a rather obvious thing for us to include.

We can implement this in two stages:
1.  Implement a mod.yaml key pointing at a url with basic mod metadata and the latest mod version.  The mod browser should check this latest version, and display a notification if an update is required.
   Mod updates are initially handled manually outside OpenRA.
2. Add a `Versions` block with openra-version specific mod information, allowing OpenRA to update to the latest version that it supports via the mod browser.

The format of the remote metadata block could look something like:

``` yaml
Title: My super mod!
Author: My awesome mod team!
PreviewImage: http://my.domain/my/mod/preview.png
LatestRelease: 3.0
Versions:
    release-20170107:
        3.0: http://my.domain/my/mod/mymodversion3.oramod
                Changelog: http://my.domain/my/mod/mymodversion3.changelog
    playtest-20161224:
        2.9-alpha3: http://my.domain/my/mod/mymodversion2.9alpha3.oramod
        2.9-alpha2: http://my.domain/my/mod/mymodversion2.9alpha2.oramod
        2.9-alpha1: http://my.domain/my/mod/mymodversion2.9alpha1.oramod
    release-20160715:
        2.0: http://my.domain/my/mod/mymodversion2.oramod
                Changelog: http://my.domain/my/mod/mymodversion2.0.changelog
```
##
