### ISSUE TITLE
Build queue provider without ProvidesPrerequisite starts with all available build options disabled

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#9056]
Tested this out with a mobile war factory using `ProductionQueue`. I assume this is intended, though but then document it.

Example setup:
```yaml
gamwrf:
	Production:
		Produces: Hanomag
	ProductionQueue@Vehicle:
		Type: Hanomag
		Group: Vehicle
		BuildSpeed: .333
		LowPowerSlowdown: 2

#Does not use explicit prerequisite, using the queue as such
hntnk:
	Buildable:	
		Queue: Hanomag
```

Without `ProvidesPrerequisite` on `gamwrf`, the queue stays disabled until the first such recheck, even though the new queue appears and `hntnk` pops up on it.
