### ISSUE TITLE
yaml inheritance breaks in conjunction with yaml removals

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#9196]
Adding the following piece of yaml to a map.yaml...

```yaml
^A:
        ProximityCaptor:
DOG:
        Inherits@a: ^A
```

... causes breakage:
```
OpenRA.Utility(1,1): Error: Actor type dog: Bogus yaml removals: TakeCover
```

It works as expected on https://github.com/pchote/OpenRA/tree/yaml-removals
