### ISSUE TITLE
Light factory production lights

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9641]
[This video](https://www.youtube.com/watch?v=AEHRiRxCR9Q) shows the Light factory (at least the Atreides one, I haven't really investigated this) having production lights at the back. Seen between 2:16 and 2:20.
Our current factory has production lights only at the front.
##

**Comment by Mailaender** [comment]
Probably a Z-sorting issue which can be solved in the sequence.yaml files.

**Comment by pchote** [comment]
Confirmed that this is caused by bogus z offsets. It looks like at least the heavy factory also has bogus offsets.

**Comment by ltem** [comment]
It also seems that the different models of the same building use only specific parts of the corresponding production-light-sequences

Example: High Tech Factory
There are lights behind the Atreides sunblinds, which doesn't exist on the Ordos building, so this part of the animation gets skipped for Ordos (Image-Source: D2K Gruntmods Edition)

Atreides            |  Ordos          
:-------------------------:|:-------------------------:
 ![hightech_atreides_lights](https://cloud.githubusercontent.com/assets/20945684/21751401/ce0c92ea-d5c6-11e6-8857-e2d972151338.png) | ![hightech_ordos_lights](https://cloud.githubusercontent.com/assets/20945684/21751402/ce0ef1d4-d5c6-11e6-9046-533f7bd03d60.png)

I'm generally interested into solving this but for now I don't know how only certain parts of the animation can be selected in the [yaml-file](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/sequences/structures.yaml#L444) as well as a good way/tool to find out which offsets are need.

**Comment by pchote** [comment]
@ltem: The `DATA.R8` file is a single giant sprite file that has all of the artwork for ingame objects.  You can select which frames are used for each of our named sequences/animations by setting the `Start` and `Length` fields in the yaml.  You can use the Asset Browser (under the Extras menu in the game) to view the frames and take note of frame numbers.

You shouldn't need to worry about the pixel offsets for fixing these issues, they come from knowing how D2K internally managed its coordinate systems (e.g. buildings were renderered relative to their bottom-left corner, tanks from their center, etc) compared to OpenRA (everything is rendered relative to their center).  The ZOffset is what you'll want to change for fixing the render order, and is measured in world units (1024 = 1 cell) and for the factories generally want to be set to whatever their roof offsets are + 1 to make sure they go on top.

**Comment by ltem** [comment]
Just to show that I'm somehow still on it.

1, If I'm correct the `ZOffset` of thestructures welding lights should be `ZOffset: 1023` (some are missing, some are `ZOffset: 511`)
2, The correct frames still have to be found

#### Support animation from GruntMods

- I don't exactly know why but in the screencast all the clips looked much more "crisp", transforming them didn't do them well
- For an other unknown reason they have an unsteady speed and are thrice as fast after cutting them to the right format but by putting them in a program like gimp, it can be watched frame by frame (or the diff of every frame to be exact). 
- This shall be more a showcase and should help for the later evaluation
- Missing "lights" are from the repair pad, IX lab and the wind traps, which are in my opinion correct, also one of the heavy fac. of Corrina is missing, didn't got a good shot on it.

| Structure | Atreides | Harkonnen | Ordos |
|:------:|:------:|:------:|:------:|
| Light Factory  |![gimp_light_a](https://cloud.githubusercontent.com/assets/20945684/23256546/354bde6c-f9c0-11e6-9ca4-fa46076fe0d1.gif) |![gimp_light_h](https://cloud.githubusercontent.com/assets/20945684/23256547/354d6214-f9c0-11e6-8ff1-b6aa222c3076.gif) | ![gimp_light_o](https://cloud.githubusercontent.com/assets/20945684/23256549/3551ca20-f9c0-11e6-98c9-a471eeb141c8.gif)|
| Heavy Factory  |![gimp_heavy_a](https://cloud.githubusercontent.com/assets/20945684/23256541/35374cb8-f9c0-11e6-8668-759cdff7b188.gif) |![gimp_heavy_h](https://cloud.githubusercontent.com/assets/20945684/23256540/35366942-f9c0-11e6-9c48-c6711fc8ad89.gif) |![gimp_heavy_o](https://cloud.githubusercontent.com/assets/20945684/23256539/35349a9a-f9c0-11e6-8081-bbdd08b6261d.gif) |
| High Tech Facotry  |![gimp_hightech_a](https://cloud.githubusercontent.com/assets/20945684/23256544/353b82a6-f9c0-11e6-96b3-970c316d487b.gif) |![gimp_hightech_h](https://cloud.githubusercontent.com/assets/20945684/23256543/353b5e84-f9c0-11e6-8a9f-e026bd6e5b66.gif) |![gimp_hightech_o](https://cloud.githubusercontent.com/assets/20945684/23256542/353a19fc-f9c0-11e6-890c-8d578dd0b8a2.gif) |
| Starport | ![gimp_star_a](https://cloud.githubusercontent.com/assets/20945684/23256548/3550ad8e-f9c0-11e6-9e9e-aee88e6037ae.gif) | ![gimp_star_h](https://cloud.githubusercontent.com/assets/20945684/23256551/35558cfa-f9c0-11e6-857b-4c168d3fc990.gif) | ![gimp_star_o](https://cloud.githubusercontent.com/assets/20945684/23256550/35542770-f9c0-11e6-8ace-36a14ba65c07.gif) |

**Comment by ltem** [comment]
So far so good, I think I found all the sequences ([LinkToMyBranch](https://github.com/ltem/OpenRA/tree/d2k-fix-lights)). In the end it was easier than expected. 

There are just two issues:

1. I changed the `ZOffset` of the top part of factories to `895` if it is `511` outcoming vehicles overlap with the structure sometimes (Devastator). 
    * Should this value be a multiplier of 32? 
    * Can this be done better? If I keep the top part at `1023` and the welding light at `1024` not all of the welding light can be seen. Is there some kind of guideline?

2. The welding lights are quite structured:
    * First `x` frames are for Atreides
    * Then `x` for Harkonnen 
    * Last `x` for Ordos

__However__, the welding lights for the heavy factory consists of 47 frames, first 30 frames are for the factions and I choose the next 10 frames for the mercenaries heavy factory (which I don't know how to test) but I have no idea what the purpose of the last 7 frames is. I mean to recognize a heavy Harkonnen factory but in my opinion there are no frames missing for them.

If concerns about these points are cleared, I would create a pull request.

**Comment by MustaphaTR** [comment]
You can test the mercenary one on O8V1 or O9V2, you can force capture them and use.

**Comment by ltem** [comment]
I tried O8V1 and added the map.yaml from CH4Code's fixed maps but I don't see the correct factory. The only difference I spotted was that the factory is called heavy.mercenary and in the yaml they are called mercenaries. I replaced it into both ways and hadn't any success. Any advices?

map.yaml head:
```yaml
MapFormat: 11

RequiresMod: d2k

Title: O8V1

Author: Westwood Studios

Tileset: ARRAKIS

MapSize: 84,104

Bounds: 2,2,80,100

Visibility: MissionSelector

Categories: Scriptless-Campaign-maps

Players:
	PlayerReference@Neutral:
		Name: Neutral
		OwnsWorld: True
		NonCombatant: True
		Faction: Random
	PlayerReference@Creeps:
		Name: Creeps
		NonCombatant: Truevim
		Faction: Random
		Enemies: Atreides, Harkonnen, Ordos, Corrino, Mercenaries, Smugglers, Fremen
	PlayerReference@Atreides:
		Name: Atreides
		Faction: atreides
		Enemies: Harkonnen, Ordos, Corrino, Mercenaries, Smugglers, Fremen, Creeps
	PlayerReference@Harkonnen:
		Name: Harkonnen
		Faction: harkonnen
		Enemies: Atreides, Ordos, Corrino, Mercenaries, Smugglers, Fremen, Creeps
	PlayerReference@Ordos:
		Playable: True
		Name: Ordos
		Faction: ordos
		LockFaction: true
		Enemies: Atreides, Harkonnen, Corrino, Mercenaries, Smugglers, Fremen, Creeps
	PlayerReference@Mercenaries:
		Name: Mercenaries
		Faction: mercenaries
		Enemies: Atreides, Harkonnen, Ordos, Corrino, Smugglers, Fremen, Creeps
	PlayerReference@Corrino:
		Name: Corrino
		Faction: harkonnen
		Enemies: Atreides, Harkonnen, Ordos, Mercenaries, Smugglers, Fremen, Creeps
	PlayerReference@Fremen:
		Name: Fremen
		Faction: atreides	
		Enemies: Atreides, Harkonnen, Ordos, Corrino, Mercenaries, Smugglers, Creeps
	PlayerReference@Smugglers:
		Name: Smugglers
		Faction: ordos
		Enemies: Atreides, Harkonnen, Ordos, Corrino, Mercenaries, Fremen, Creeps
Rules:
	Player:
		-ConquestVictoryConditions:
			EarlyGameOver: True
	World:
		-SpawnMPUnits:
		-MPStartLocations:
Actors: yadayada
```
